sudo: required
services:
  - docker
before_install:
  - docker build -t hasnatsafder/docker-react -f Dockerfile.dev .
script:
  - docker run hasnatsafder/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-reach"
  env: "DockerReach-env"
  bucket_name: "elasticbeanstalk-us-east-2-065921359170"
  bucket_path: "docker-reach"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

